services:

  mysql5734:
    image: "mysql:5.7.34"
    command: ["--wait_timeout=30"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
  # backend:
  #   build:
  #     context: ./
  #     dockerfile: ./backend/Dockerfile
  #   command: yarn dev
  #   volumes:
  #     - ./backend:/application
  #     - ./backend/node_modules:/application/node_modules
  #   ports:
  #     - 5000:5000